# Generated by Django 4.2.4 on 2023-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_gpt_post_gpt_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpt_call',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
