# Generated by Django 4.2.4 on 2023-10-04 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=255)),
                ('graph_structure', models.TextField(null=True)),
                ('achieve_percentage', models.PositiveIntegerField(default=0)),
                ('total_nodes', models.PositiveIntegerField(default=0)),
                ('cleared_nodes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('level', models.PositiveIntegerField(default=0)),
                ('exp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('example', models.TextField(null=True)),
                ('question', models.TextField(null=True)),
                ('question_a', models.TextField(null=True)),
                ('question_b', models.TextField(null=True)),
                ('question_c', models.TextField(null=True)),
                ('question_d', models.TextField(null=True)),
                ('true_answer', models.CharField(max_length=10, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_extra_node', models.BooleanField(default=False)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('child_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='api.node')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='api.node')),
            ],
        ),
    ]
