# Generated by Django 4.2.4 on 2023-09-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gpt_call_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpt_call',
            name='author',
        ),
    ]
