# Generated by Django 4.2.4 on 2023-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_map_user_node_map_user_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='x_coordinate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='node',
            name='y_coordinate',
            field=models.FloatField(default=0.0),
        ),
    ]
