# Generated by Django 4.2.4 on 2023-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_node_title_alter_node_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
