# Generated by Django 4.2.4 on 2023-10-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_map_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
    ]
