# Generated by Django 4.2.4 on 2023-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_node_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='child_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='api.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='parent_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='api.node'),
        ),
        migrations.AlterField(
            model_name='map',
            name='theme_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
